### ISSUE TITLE
Add request origination self identifier for DMSDK metrics

### ISSUE THREAD

**Issue by popzip** [marklogic/data-movement#137]
Using Telemetry, we can track feature usage at a granular level. For example, the Optic API will be tracking # of joins. We need a way to track where a request originated when coming from the Client APIs. Each client API must include some sort of identifier that the server can use to increment the correct metric (e.g. search-xquery vs search-dmsdk ?? not sure if that's even a valid example).

This task is not for a specific metric - just adding the DMSDK identifier that can be used by feature tracking mechanism. 
(This also exists for Java API and I am unclear on the separation of functionality between these two libraries but wanted to make sure we had complete coverage - https://github.com/marklogic/java-client-api/issues/473)

**Comment by sammefford** [comment]
@popzip @ehennum what do you guys think about keeping DMSDK separate in telemetry now that it's part of the java-client API?  I'm thinking we don't want to treat DMSDK as a separate client, so we should probably just think in a future release about ways to track DMSDK usage as a feature similar to but separate from bulk CRUD calls (even though it builds on top of bulk CRUD).  Does that sound reasonable?

**Comment by popzip** [comment]
Question for @jmakeig 
The point is more around tracking usage of different features. Want to make sure you measure/touch on aspects introduced by the DMSDK enhancements to Java Client API but does not need to be a specific bucket.

**Comment by ehennum** [comment]
That makes sense to me @sammefford 

If we put telemetry on the internal request that gets the uris, that gives us a metric with isolation on DMSDK, no?

**Comment by sammefford** [comment]
sure, telemetry on requests to /v1/internal/uris would track requests to that endpoint, which currently only come from DMSDK.  But it wouldn't track any CRUD request made by WriteBatcher, ExportListener, or DeleteListener.  I'm thinking I'd like to track those separately from other bulk CRUD requests even though they build on top of the bulk CRUD apis.

**Comment by sammefford** [comment]
@popzip I could see us using ML-Agent-ID "dmsdk.java" rather than "java" for requests made by dmsdk.  Does that make sense?  Otherwise there will be no way to differentiate, since DMSDK builds on top of the Java Client API Bulk read/write/delete.

As it currently stands, we should be able to track searches by DMSDK if we track usage of the (internal use only) /v1/internal/uris REST endpoint since it's the only thing that currently uses that endpoint.  But what is done with those uris in subsequent requests won't be marked as DMSDK.  Similarly, DMSDK will be the only thing making requests to the (internal use only) /v1/internal/forestinfo REST endpoint and the /v1/internal/apply-transform REST endpoints, so we could track those.

Do you want me to move ahead with a "dmsdk.java" agent id?

**Comment by popzip** [comment]
I'm not sure of the hierarchy, i'll defer to @jmakeig but it seems like java should still be the agent and dmsdk is some subset measurement of which endpoints/functions are being used within java.

**Comment by sammefford** [comment]
Hmm, I guess we need a task to open up another way for Java to identify which features are being used, rather than just trying to identify it at the REST level . . .

**Comment by sammefford** [comment]
Ok, I'm closing this and instead I opened https://github.com/marklogic/java-client-api/issues/654

**Comment by popzip** [comment]
yes makes sense
