### ISSUE TITLE
withOutputLanguage(String xmlLang) function missing in AggregatesImportDefinition class

### ISSUE THREAD

**Issue by srinathgit** [marklogic/data-movement#23]
The following test uses aggregates input along with language option set to 'en'. But the corresponding method is not available in AggregatesImportDefinition  class

mlcp.sh  import -username admin -password admin -host localhost -port 5275 -input_file_type aggregates -aggregate_record_element baz -aggregate_uri_id @uri-id -output_collections fooo,bar,baz -input_file_path QA_HOME/mlcp/data/agg/nested2 **-output_language en** -output_directory /dir3 -output_quality 3 -output_permissions dls-user,read

**Comment by sammefford** [comment]
For some reason I only had output language on delimited text and json.  But I can see now how it could apply to any input file type that allows non-xml files.  However, I can't see how it makes sense for input file type aggregates because those are all xml and therefore could specify the xml:lang in the content.  Oh well, if mlcp supports it our wrappers should.  So I've moved output language to ImportDefinition so it will work for all input file types.

**Comment by srinathgit** [comment]
Closing this out as DMSDK does not use mlcp
