### ISSUE TITLE
Support in DMSDK for scenarios where only options file is specified

### ISSUE THREAD

**Issue by srinathgit** [marklogic/data-movement#24]
In the example below, mlcp is invoked without specifying the input command (import, export etc). We don't have support for such scenarios currently in DMSDK. 

mlcp.sh  -options_file QA_HOME/mlcp/data/export/input-files/export-2.txt

**Comment by sammefford** [comment]
Thanks for pointing out that apparently mlcp supports this scenario.  Since DMSDK wrappers of mlcp are significantly reduced priority right now, I'm marking this "will not fix".  We can re-open this issue if/when we prioritize the mlcp wrappers.  Nevertheless, I'll give my opinion that we could just decide that dmsdk doesn't support this scenario.  If you don't even know whether you're doing an import, export, or copy, it seems you should use mlcp directly and not the dmsdk wrappers.
